from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(228, 168)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.AxisCB = QtWidgets.QComboBox(Form)
        self.AxisCB.setObjectName("AxisCB")
        self.AxisCB.addItem("")
        self.AxisCB.addItem("")
        self.AxisCB.addItem("")
        self.horizontalLayout_3.addWidget(self.AxisCB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.VecXCK = QtWidgets.QCheckBox(Form)
        self.VecXCK.setChecked(True)
        self.VecXCK.setObjectName("VecXCK")
        self.horizontalLayout_2.addWidget(self.VecXCK)
        self.VecYCK = QtWidgets.QCheckBox(Form)
        self.VecYCK.setChecked(True)
        self.VecYCK.setObjectName("VecYCK")
        self.horizontalLayout_2.addWidget(self.VecYCK)
        self.VecZCK = QtWidgets.QCheckBox(Form)
        self.VecZCK.setChecked(True)
        self.VecZCK.setObjectName("VecZCK")
        self.horizontalLayout_2.addWidget(self.VecZCK)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RVecXCK = QtWidgets.QCheckBox(Form)
        self.RVecXCK.setChecked(True)
        self.RVecXCK.setObjectName("RVecXCK")
        self.horizontalLayout.addWidget(self.RVecXCK)
        self.RVecYCK = QtWidgets.QCheckBox(Form)
        self.RVecYCK.setChecked(True)
        self.RVecYCK.setObjectName("RVecYCK")
        self.horizontalLayout.addWidget(self.RVecYCK)
        self.RVecZCK = QtWidgets.QCheckBox(Form)
        self.RVecZCK.setChecked(True)
        self.RVecZCK.setObjectName("RVecZCK")
        self.horizontalLayout.addWidget(self.RVecZCK)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.createPB = QtWidgets.QPushButton(Form)
        self.createPB.setObjectName("createPB")
        self.verticalLayout.addWidget(self.createPB)
        self.removePB = QtWidgets.QPushButton(Form)
        self.removePB.setObjectName("removePB")
        self.verticalLayout.addWidget(self.removePB)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Pose Reader", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Axis : ", None, -1))
        self.AxisCB.setItemText(0, QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.AxisCB.setItemText(1, QtWidgets.QApplication.translate("Form", "y", None, -1))
        self.AxisCB.setItemText(2, QtWidgets.QApplication.translate("Form", "z", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Vector : ", None, -1))
        self.VecXCK.setText(QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.VecYCK.setText(QtWidgets.QApplication.translate("Form", "y", None, -1))
        self.VecZCK.setText(QtWidgets.QApplication.translate("Form", "z", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Reverse Vector : ", None, -1))
        self.RVecXCK.setText(QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.RVecYCK.setText(QtWidgets.QApplication.translate("Form", "y", None, -1))
        self.RVecZCK.setText(QtWidgets.QApplication.translate("Form", "z", None, -1))
        self.createPB.setText(QtWidgets.QApplication.translate("Form", "Create", None, -1))
        self.removePB.setText(QtWidgets.QApplication.translate("Form", "Remove", None, -1))