from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CNTManager(object):
    def setupUi(self, CNTManager):
        CNTManager.setObjectName("CNTManager")
        CNTManager.resize(430, 650)
        self.gridLayout_3 = QtWidgets.QGridLayout(CNTManager)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.AlistWidget = QtWidgets.QListWidget(CNTManager)
        self.AlistWidget.setDragEnabled(True)
        self.AlistWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.AlistWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.AlistWidget.setObjectName("AlistWidget")
        self.gridLayout.addWidget(self.AlistWidget, 0, 0, 1, 2)
        self.AAddPB = QtWidgets.QPushButton(CNTManager)
        self.AAddPB.setObjectName("AAddPB")
        self.gridLayout.addWidget(self.AAddPB, 1, 0, 1, 1)
        self.ARemovePB = QtWidgets.QPushButton(CNTManager)
        self.ARemovePB.setObjectName("ARemovePB")
        self.gridLayout.addWidget(self.ARemovePB, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.SortPB = QtWidgets.QPushButton(CNTManager)
        self.SortPB.setFlat(True)
        self.SortPB.setObjectName("SortPB")
        self.verticalLayout_3.addWidget(self.SortPB)
        self.ChangePB = QtWidgets.QPushButton(CNTManager)
        self.ChangePB.setFlat(True)
        self.ChangePB.setObjectName("ChangePB")
        self.verticalLayout_3.addWidget(self.ChangePB)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.OneToNRB = QtWidgets.QRadioButton(CNTManager)
        self.OneToNRB.setChecked(False)
        self.OneToNRB.setObjectName("OneToNRB")
        self.verticalLayout.addWidget(self.OneToNRB)
        self.NToNRB = QtWidgets.QRadioButton(CNTManager)
        self.NToNRB.setChecked(True)
        self.NToNRB.setObjectName("NToNRB")
        self.verticalLayout.addWidget(self.NToNRB)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BlistWidget = QtWidgets.QListWidget(CNTManager)
        self.BlistWidget.setDragEnabled(True)
        self.BlistWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.BlistWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.BlistWidget.setObjectName("BlistWidget")
        self.gridLayout_2.addWidget(self.BlistWidget, 0, 0, 1, 2)
        self.BAddPB = QtWidgets.QPushButton(CNTManager)
        self.BAddPB.setObjectName("BAddPB")
        self.gridLayout_2.addWidget(self.BAddPB, 1, 0, 1, 1)
        self.BRemovePB = QtWidgets.QPushButton(CNTManager)
        self.BRemovePB.setObjectName("BRemovePB")
        self.gridLayout_2.addWidget(self.BRemovePB, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OutLE = QtWidgets.QLineEdit(CNTManager)
        self.OutLE.setObjectName("OutLE")
        self.horizontalLayout_2.addWidget(self.OutLE)
        self.ConnectionPB = QtWidgets.QPushButton(CNTManager)
        self.ConnectionPB.setFlat(True)
        self.ConnectionPB.setObjectName("ConnectionPB")
        self.horizontalLayout_2.addWidget(self.ConnectionPB)
        self.InLE = QtWidgets.QLineEdit(CNTManager)
        self.InLE.setObjectName("InLE")
        self.horizontalLayout_2.addWidget(self.InLE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GetSetPB = QtWidgets.QPushButton(CNTManager)
        self.GetSetPB.setObjectName("GetSetPB")
        self.horizontalLayout_3.addWidget(self.GetSetPB)
        self.PPPB = QtWidgets.QPushButton(CNTManager)
        self.PPPB.setObjectName("PPPB")
        self.horizontalLayout_3.addWidget(self.PPPB)
        self.SetDrivenPB = QtWidgets.QPushButton(CNTManager)
        self.SetDrivenPB.setObjectName("SetDrivenPB")
        self.horizontalLayout_3.addWidget(self.SetDrivenPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(CNTManager)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AllCKB = QtWidgets.QCheckBox(CNTManager)
        self.AllCKB.setChecked(True)
        self.AllCKB.setObjectName("AllCKB")
        self.horizontalLayout.addWidget(self.AllCKB)
        self.TransCKB = QtWidgets.QCheckBox(CNTManager)
        self.TransCKB.setChecked(False)
        self.TransCKB.setObjectName("TransCKB")
        self.horizontalLayout.addWidget(self.TransCKB)
        self.RotCKB = QtWidgets.QCheckBox(CNTManager)
        self.RotCKB.setObjectName("RotCKB")
        self.horizontalLayout.addWidget(self.RotCKB)
        self.ScaleCKB = QtWidgets.QCheckBox(CNTManager)
        self.ScaleCKB.setObjectName("ScaleCKB")
        self.horizontalLayout.addWidget(self.ScaleCKB)
        self.ShearCKB = QtWidgets.QCheckBox(CNTManager)
        self.ShearCKB.setObjectName("ShearCKB")
        self.horizontalLayout.addWidget(self.ShearCKB)
        self.PivotCKB = QtWidgets.QCheckBox(CNTManager)
        self.PivotCKB.setChecked(True)
        self.PivotCKB.setObjectName("PivotCKB")
        self.horizontalLayout.addWidget(self.PivotCKB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.MatchPB = QtWidgets.QPushButton(CNTManager)
        self.MatchPB.setObjectName("MatchPB")
        self.horizontalLayout_4.addWidget(self.MatchPB)
        self.MConPB = QtWidgets.QPushButton(CNTManager)
        self.MConPB.setObjectName("MConPB")
        self.horizontalLayout_4.addWidget(self.MConPB)
        self.ConstPB = QtWidgets.QPushButton(CNTManager)
        self.ConstPB.setObjectName("ConstPB")
        self.horizontalLayout_4.addWidget(self.ConstPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AUTHORLB = QtWidgets.QLabel(CNTManager)
        self.AUTHORLB.setAlignment(QtCore.Qt.AlignCenter)
        self.AUTHORLB.setObjectName("AUTHORLB")
        self.verticalLayout_4.addWidget(self.AUTHORLB)
        self.UPDATALB = QtWidgets.QLabel(CNTManager)
        self.UPDATALB.setAlignment(QtCore.Qt.AlignCenter)
        self.UPDATALB.setObjectName("UPDATALB")
        self.verticalLayout_4.addWidget(self.UPDATALB)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 0, 1, 1)

        self.retranslateUi(CNTManager)
        QtCore.QMetaObject.connectSlotsByName(CNTManager)

    def retranslateUi(self, CNTManager):
        CNTManager.setWindowTitle(QtWidgets.QApplication.translate("CNTManager", "CNTManager", None, -1))
        self.AAddPB.setText(QtWidgets.QApplication.translate("CNTManager", "Add", None, -1))
        self.ARemovePB.setText(QtWidgets.QApplication.translate("CNTManager", "Remove", None, -1))
        self.SortPB.setText(QtWidgets.QApplication.translate("CNTManager", "Sort", None, -1))
        self.ChangePB.setText(QtWidgets.QApplication.translate("CNTManager", "Change", None, -1))
        self.OneToNRB.setText(QtWidgets.QApplication.translate("CNTManager", "One To N", None, -1))
        self.NToNRB.setText(QtWidgets.QApplication.translate("CNTManager", "N To N", None, -1))
        self.BAddPB.setText(QtWidgets.QApplication.translate("CNTManager", "Add", None, -1))
        self.BRemovePB.setText(QtWidgets.QApplication.translate("CNTManager", "Remove", None, -1))
        self.OutLE.setText(QtWidgets.QApplication.translate("CNTManager", "OutPut..", None, -1))
        self.ConnectionPB.setText(QtWidgets.QApplication.translate("CNTManager", ">>", None, -1))
        self.InLE.setText(QtWidgets.QApplication.translate("CNTManager", "InPut..", None, -1))
        self.GetSetPB.setText(QtWidgets.QApplication.translate("CNTManager", "Get Set", None, -1))
        self.PPPB.setText(QtWidgets.QApplication.translate("CNTManager", "PParent", None, -1))
        self.SetDrivenPB.setText(QtWidgets.QApplication.translate("CNTManager", "SetDriven", None, -1))
        self.AllCKB.setText(QtWidgets.QApplication.translate("CNTManager", "All", None, -1))
        self.TransCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Trans", None, -1))
        self.RotCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Rot", None, -1))
        self.ScaleCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Scale", None, -1))
        self.ShearCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Shear", None, -1))
        self.PivotCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Pivot", None, -1))
        self.MatchPB.setText(QtWidgets.QApplication.translate("CNTManager", "Match", None, -1))
        self.MConPB.setText(QtWidgets.QApplication.translate("CNTManager", "MCon", None, -1))
        self.ConstPB.setText(QtWidgets.QApplication.translate("CNTManager", "Const", None, -1))
        self.AUTHORLB.setText(QtWidgets.QApplication.translate("CNTManager", "AUTHOR : MinSung", None, -1))
        self.UPDATALB.setText(QtWidgets.QApplication.translate("CNTManager", "UPDATE : 20220114", None, -1))
        self.PivotCKB.setObjectName("PivotCKB")
        self.horizontalLayout.addWidget(self.PivotCKB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.MatchPB = QtWidgets.QPushButton(CNTManager)
        self.MatchPB.setObjectName("MatchPB")
        self.horizontalLayout_4.addWidget(self.MatchPB)
        self.MConPB = QtWidgets.QPushButton(CNTManager)
        self.MConPB.setObjectName("MConPB")
        self.horizontalLayout_4.addWidget(self.MConPB)
        self.ConstPB = QtWidgets.QPushButton(CNTManager)
        self.ConstPB.setObjectName("ConstPB")
        self.horizontalLayout_4.addWidget(self.ConstPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AUTHORLB = QtWidgets.QLabel(CNTManager)
        self.AUTHORLB.setAlignment(QtCore.Qt.AlignCenter)
        self.AUTHORLB.setObjectName("AUTHORLB")
        self.verticalLayout_4.addWidget(self.AUTHORLB)
        self.UPDATALB = QtWidgets.QLabel(CNTManager)
        self.UPDATALB.setAlignment(QtCore.Qt.AlignCenter)
        self.UPDATALB.setObjectName("UPDATALB")
        self.verticalLayout_4.addWidget(self.UPDATALB)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 0, 1, 1)

        self.retranslateUi(CNTManager)
        QtCore.QMetaObject.connectSlotsByName(CNTManager)

    def retranslateUi(self, CNTManager):
        CNTManager.setWindowTitle(QtWidgets.QApplication.translate("CNTManager", "CNTManager", None, -1))
        self.AAddPB.setText(QtWidgets.QApplication.translate("CNTManager", "Add", None, -1))
        self.ARemovePB.setText(QtWidgets.QApplication.translate("CNTManager", "Remove", None, -1))
        self.SortPB.setText(QtWidgets.QApplication.translate("CNTManager", "Sort", None, -1))
        self.ChangePB.setText(QtWidgets.QApplication.translate("CNTManager", "Change", None, -1))
        self.OneToNRB.setText(QtWidgets.QApplication.translate("CNTManager", "One To N", None, -1))
        self.NToNRB.setText(QtWidgets.QApplication.translate("CNTManager", "N To N", None, -1))
        self.BAddPB.setText(QtWidgets.QApplication.translate("CNTManager", "Add", None, -1))
        self.BRemovePB.setText(QtWidgets.QApplication.translate("CNTManager", "Remove", None, -1))
        self.OutLE.setText(QtWidgets.QApplication.translate("CNTManager", "OutPut..", None, -1))
        self.ConnectionPB.setText(QtWidgets.QApplication.translate("CNTManager", ">>", None, -1))
        self.InLE.setText(QtWidgets.QApplication.translate("CNTManager", "InPut..", None, -1))
        self.GetSetPB.setText(QtWidgets.QApplication.translate("CNTManager", "Get Set", None, -1))
        self.PPPB.setText(QtWidgets.QApplication.translate("CNTManager", "PParent", None, -1))
        self.SetDrivenPB.setText(QtWidgets.QApplication.translate("CNTManager", "SetDriven", None, -1))
        self.AllCKB.setText(QtWidgets.QApplication.translate("CNTManager", "All", None, -1))
        self.TransCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Trans", None, -1))
        self.RotCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Rot", None, -1))
        self.ScaleCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Scale", None, -1))
        self.ShearCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Shear", None, -1))
        self.PivotCKB.setText(QtWidgets.QApplication.translate("CNTManager", "Pivot", None, -1))
        self.MatchPB.setText(QtWidgets.QApplication.translate("CNTManager", "Match", None, -1))
        self.MConPB.setText(QtWidgets.QApplication.translate("CNTManager", "MCon", None, -1))
        self.ConstPB.setText(QtWidgets.QApplication.translate("CNTManager", "Const", None, -1))
        self.AUTHORLB.setText(QtWidgets.QApplication.translate("CNTManager", "AUTHOR : MinSung", None, -1))
        self.UPDATALB.setText(QtWidgets.QApplication.translate("CNTManager", "UPDATE : 20220114", None, -1))