from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(243, 593)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(245, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelCB = QtWidgets.QComboBox(Form)
        self.labelCB.setObjectName("labelCB")
        self.horizontalLayout.addWidget(self.labelCB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sideCB = QtWidgets.QComboBox(Form)
        self.sideCB.setObjectName("sideCB")
        self.horizontalLayout_2.addWidget(self.sideCB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelBT = QtWidgets.QPushButton(Form)
        self.labelBT.setObjectName("labelBT")
        self.verticalLayout.addWidget(self.labelBT)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        spacerItem1 = QtWidgets.QSpacerItem(245, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.numSP = QtWidgets.QSpinBox(Form)
        self.numSP.setProperty("value", 3)
        self.numSP.setObjectName("numSP")
        self.horizontalLayout_3.addWidget(self.numSP)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.LSJAxisCB = QtWidgets.QComboBox(Form)
        self.LSJAxisCB.setObjectName("LSJAxisCB")
        self.LSJAxisCB.addItem("")
        self.LSJAxisCB.addItem("")
        self.LSJAxisCB.addItem("")
        self.LSJAxisCB.addItem("")
        self.LSJAxisCB.addItem("")
        self.LSJAxisCB.addItem("")
        self.horizontalLayout_4.addWidget(self.LSJAxisCB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.LSJBT = QtWidgets.QPushButton(Form)
        self.LSJBT.setObjectName("LSJBT")
        self.verticalLayout.addWidget(self.LSJBT)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(245, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.ojCB = QtWidgets.QComboBox(Form)
        self.ojCB.setObjectName("ojCB")
        self.ojCB.addItem("")
        self.ojCB.addItem("")
        self.ojCB.addItem("")
        self.ojCB.addItem("")
        self.ojCB.addItem("")
        self.ojCB.addItem("")
        self.horizontalLayout_5.addWidget(self.ojCB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.saoCB = QtWidgets.QComboBox(Form)
        self.saoCB.setObjectName("saoCB")
        self.saoCB.addItem("")
        self.saoCB.addItem("")
        self.saoCB.addItem("")
        self.saoCB.addItem("")
        self.saoCB.addItem("")
        self.saoCB.addItem("")
        self.horizontalLayout_6.addWidget(self.saoCB)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.JOBT = QtWidgets.QPushButton(Form)
        self.JOBT.setObjectName("JOBT")
        self.verticalLayout.addWidget(self.JOBT)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem3 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.OMAxisCB = QtWidgets.QComboBox(Form)
        self.OMAxisCB.setObjectName("OMAxisCB")
        self.OMAxisCB.addItem("")
        self.OMAxisCB.addItem("")
        self.OMAxisCB.addItem("")
        self.OMAxisCB.addItem("")
        self.OMAxisCB.addItem("")
        self.OMAxisCB.addItem("")
        self.horizontalLayout_7.addWidget(self.OMAxisCB)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.OMCB = QtWidgets.QPushButton(Form)
        self.OMCB.setObjectName("OMCB")
        self.verticalLayout.addWidget(self.OMCB)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)

        self.retranslateUi(Form)
        self.ojCB.setCurrentIndex(1)
        self.saoCB.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "### Joint Labeling ###", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Label Name :", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Side :", None, -1))
        self.labelBT.setText(QtWidgets.QApplication.translate("Form", "Labeling", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "# Execute after selecting the top joint", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "### Linear Spacing Joint ###", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Number :", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "Axis :", None, -1))
        self.LSJAxisCB.setItemText(0, QtWidgets.QApplication.translate("Form", "x", None, -1))
        self.LSJAxisCB.setItemText(1, QtWidgets.QApplication.translate("Form", "y", None, -1))
        self.LSJAxisCB.setItemText(2, QtWidgets.QApplication.translate("Form", "z", None, -1))
        self.LSJAxisCB.setItemText(3, QtWidgets.QApplication.translate("Form", "-x", None, -1))
        self.LSJAxisCB.setItemText(4, QtWidgets.QApplication.translate("Form", "-y", None, -1))
        self.LSJAxisCB.setItemText(5, QtWidgets.QApplication.translate("Form", "-z", None, -1))
        self.LSJBT.setText(QtWidgets.QApplication.translate("Form", "PushButton", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "# Execute after selecting the top joint", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "### Joint Orient ###", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "OrientJoint :", None, -1))
        self.ojCB.setItemText(0, QtWidgets.QApplication.translate("Form", "xyz", None, -1))
        self.ojCB.setItemText(1, QtWidgets.QApplication.translate("Form", "xzy", None, -1))
        self.ojCB.setItemText(2, QtWidgets.QApplication.translate("Form", "yxz", None, -1))
        self.ojCB.setItemText(3, QtWidgets.QApplication.translate("Form", "yzx", None, -1))
        self.ojCB.setItemText(4, QtWidgets.QApplication.translate("Form", "zxy", None, -1))
        self.ojCB.setItemText(5, QtWidgets.QApplication.translate("Form", "zyx", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "SecondaryAxisOrient :", None, -1))
        self.saoCB.setItemText(0, QtWidgets.QApplication.translate("Form", "xup", None, -1))
        self.saoCB.setItemText(1, QtWidgets.QApplication.translate("Form", "xdown", None, -1))
        self.saoCB.setItemText(2, QtWidgets.QApplication.translate("Form", "yup", None, -1))
        self.saoCB.setItemText(3, QtWidgets.QApplication.translate("Form", "ydown", None, -1))
        self.saoCB.setItemText(4, QtWidgets.QApplication.translate("Form", "zup", None, -1))
        self.saoCB.setItemText(5, QtWidgets.QApplication.translate("Form", "zdown", None, -1))
        self.JOBT.setText(QtWidgets.QApplication.translate("Form", "JointOrient", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", "# Execute after selecting the top joint", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "### Object Mirror ###", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Axis :", None, -1))
        self.OMAxisCB.setItemText(0, QtWidgets.QApplication.translate("Form", "xy", None, -1))
        self.OMAxisCB.setItemText(1, QtWidgets.QApplication.translate("Form", "xz", None, -1))
        self.OMAxisCB.setItemText(2, QtWidgets.QApplication.translate("Form", "yx", None, -1))
        self.OMAxisCB.setItemText(3, QtWidgets.QApplication.translate("Form", "yz", None, -1))
        self.OMAxisCB.setItemText(4, QtWidgets.QApplication.translate("Form", "zx", None, -1))
        self.OMAxisCB.setItemText(5, QtWidgets.QApplication.translate("Form", "zy", None, -1))
        self.OMCB.setText(QtWidgets.QApplication.translate("Form", "Mirror", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Form", "# Select an item and target and execute", None, -1))