from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 713)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.rename_tap = QtWidgets.QWidget()
        self.rename_tap.setObjectName("rename_tap")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rename_tap)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.rename_tap)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.rename_tap)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_lineEdit = QtWidgets.QLineEdit(self.rename_tap)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout_2.addWidget(self.name_lineEdit)
        self.padding_lineEdit = QtWidgets.QLineEdit(self.rename_tap)
        self.padding_lineEdit.setObjectName("padding_lineEdit")
        self.horizontalLayout_2.addWidget(self.padding_lineEdit)
        self.rename_pushButton = QtWidgets.QPushButton(self.rename_tap)
        self.rename_pushButton.setObjectName("rename_pushButton")
        self.horizontalLayout_2.addWidget(self.rename_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_9 = QtWidgets.QFrame(self.rename_tap)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        self.label_20 = QtWidgets.QLabel(self.rename_tap)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prefix_lineEdit = QtWidgets.QLineEdit(self.rename_tap)
        self.prefix_lineEdit.setObjectName("prefix_lineEdit")
        self.horizontalLayout_3.addWidget(self.prefix_lineEdit)
        self.suffix_lineEdit = QtWidgets.QLineEdit(self.rename_tap)
        self.suffix_lineEdit.setObjectName("suffix_lineEdit")
        self.horizontalLayout_3.addWidget(self.suffix_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_10 = QtWidgets.QFrame(self.rename_tap)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.label_21 = QtWidgets.QLabel(self.rename_tap)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.oldname_lineEdit = QtWidgets.QLineEdit(self.rename_tap)
        self.oldname_lineEdit.setObjectName("oldname_lineEdit")
        self.horizontalLayout_4.addWidget(self.oldname_lineEdit)
        self.newname_lineEdit = QtWidgets.QLineEdit(self.rename_tap)
        self.newname_lineEdit.setObjectName("newname_lineEdit")
        self.horizontalLayout_4.addWidget(self.newname_lineEdit)
        self.change_pushButton = QtWidgets.QPushButton(self.rename_tap)
        self.change_pushButton.setObjectName("change_pushButton")
        self.horizontalLayout_4.addWidget(self.change_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.message_label = QtWidgets.QLabel(self.rename_tap)
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.verticalLayout_2.addWidget(self.message_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 330, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.rename_tap, "")
        self.rigSupport_tap = QtWidgets.QWidget()
        self.rigSupport_tap.setObjectName("rigSupport_tap")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rigSupport_tap)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.line_5 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.baseName_lineEdit = QtWidgets.QLineEdit(self.rigSupport_tap)
        self.baseName_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.baseName_lineEdit.setObjectName("baseName_lineEdit")
        self.verticalLayout.addWidget(self.baseName_lineEdit)
        self.line_15 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout.addWidget(self.line_15)
        self.label = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spacingNum_spinBox = QtWidgets.QSpinBox(self.rigSupport_tap)
        self.spacingNum_spinBox.setProperty("value", 3)
        self.spacingNum_spinBox.setObjectName("spacingNum_spinBox")
        self.horizontalLayout.addWidget(self.spacingNum_spinBox)
        self.label_18 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.oj_comboBox = QtWidgets.QComboBox(self.rigSupport_tap)
        self.oj_comboBox.setObjectName("oj_comboBox")
        self.oj_comboBox.addItem("")
        self.oj_comboBox.addItem("")
        self.oj_comboBox.addItem("")
        self.oj_comboBox.addItem("")
        self.oj_comboBox.addItem("")
        self.oj_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.oj_comboBox)
        self.sao_comboBox = QtWidgets.QComboBox(self.rigSupport_tap)
        self.sao_comboBox.setObjectName("sao_comboBox")
        self.sao_comboBox.addItem("")
        self.sao_comboBox.addItem("")
        self.sao_comboBox.addItem("")
        self.sao_comboBox.addItem("")
        self.sao_comboBox.addItem("")
        self.sao_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.sao_comboBox)
        self.LSJoint_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.LSJoint_pushButton.setObjectName("LSJoint_pushButton")
        self.horizontalLayout.addWidget(self.LSJoint_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.rigSupport_tap)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_5 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.main_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.main_pushButton.setObjectName("main_pushButton")
        self.verticalLayout.addWidget(self.main_pushButton)
        self.line_2 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_8 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.paramSpace_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.paramSpace_pushButton.setObjectName("paramSpace_pushButton")
        self.verticalLayout.addWidget(self.paramSpace_pushButton)
        self.line_3 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_9 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_4 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.hybrid_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.hybrid_pushButton.setObjectName("hybrid_pushButton")
        self.verticalLayout.addWidget(self.hybrid_pushButton)
        self.line_4 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_10 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.objCV_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.objCV_pushButton.setObjectName("objCV_pushButton")
        self.horizontalLayout_8.addWidget(self.objCV_pushButton)
        self.crvNull_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.crvNull_pushButton.setObjectName("crvNull_pushButton")
        self.horizontalLayout_8.addWidget(self.crvNull_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.attach_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.attach_pushButton.setObjectName("attach_pushButton")
        self.verticalLayout.addWidget(self.attach_pushButton)
        self.line_6 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.label_13 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.switchImport_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.switchImport_pushButton.setObjectName("switchImport_pushButton")
        self.verticalLayout.addWidget(self.switchImport_pushButton)
        self.line_7 = QtWidgets.QFrame(self.rigSupport_tap)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.label_14 = QtWidgets.QLabel(self.rigSupport_tap)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.rigSupport_tap)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.shapeChange_pushButton = QtWidgets.QPushButton(self.rigSupport_tap)
        self.shapeChange_pushButton.setObjectName("shapeChange_pushButton")
        self.verticalLayout.addWidget(self.shapeChange_pushButton)
        self.tabWidget.addTab(self.rigSupport_tap, "")
        self.moduleBuilder_tap = QtWidgets.QWidget()
        self.moduleBuilder_tap.setObjectName("moduleBuilder_tap")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.moduleBuilder_tap)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_30 = QtWidgets.QLabel(self.moduleBuilder_tap)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_4.addWidget(self.label_30)
        self.line_11 = QtWidgets.QFrame(self.moduleBuilder_tap)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_4.addWidget(self.line_11)
        self.label_22 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.M_prefix_lineEdit = QtWidgets.QLineEdit(self.moduleBuilder_tap)
        self.M_prefix_lineEdit.setObjectName("M_prefix_lineEdit")
        self.verticalLayout_4.addWidget(self.M_prefix_lineEdit)
        self.module_comboBox = QtWidgets.QComboBox(self.moduleBuilder_tap)
        self.module_comboBox.setObjectName("module_comboBox")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.module_comboBox)
        self.import_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.import_pushButton.setObjectName("import_pushButton")
        self.verticalLayout_4.addWidget(self.import_pushButton)
        self.label_25 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.mirror_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.mirror_pushButton.setObjectName("mirror_pushButton")
        self.verticalLayout_4.addWidget(self.mirror_pushButton)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.build_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.build_pushButton.setObjectName("build_pushButton")
        self.horizontalLayout_7.addWidget(self.build_pushButton)
        self.rebuild_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.rebuild_pushButton.setObjectName("rebuild_pushButton")
        self.horizontalLayout_7.addWidget(self.rebuild_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_14 = QtWidgets.QFrame(self.moduleBuilder_tap)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_4.addWidget(self.line_14)
        self.label_26 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_29 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bendType_comboBox = QtWidgets.QComboBox(self.moduleBuilder_tap)
        self.bendType_comboBox.setObjectName("bendType_comboBox")
        self.bendType_comboBox.addItem("")
        self.bendType_comboBox.addItem("")
        self.horizontalLayout_6.addWidget(self.bendType_comboBox)
        self.bendAdd_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.bendAdd_pushButton.setObjectName("bendAdd_pushButton")
        self.horizontalLayout_6.addWidget(self.bendAdd_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.line_12 = QtWidgets.QFrame(self.moduleBuilder_tap)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_4.addWidget(self.line_12)
        self.label_27 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_23 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.parent_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.parent_pushButton.setObjectName("parent_pushButton")
        self.verticalLayout_4.addWidget(self.parent_pushButton)
        self.line_13 = QtWidgets.QFrame(self.moduleBuilder_tap)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_4.addWidget(self.line_13)
        self.label_28 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.label_24 = QtWidgets.QLabel(self.moduleBuilder_tap)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.followEnum_lineEdit = QtWidgets.QLineEdit(self.moduleBuilder_tap)
        self.followEnum_lineEdit.setObjectName("followEnum_lineEdit")
        self.horizontalLayout_5.addWidget(self.followEnum_lineEdit)
        self.followAdd_pushButton = QtWidgets.QPushButton(self.moduleBuilder_tap)
        self.followAdd_pushButton.setObjectName("followAdd_pushButton")
        self.horizontalLayout_5.addWidget(self.followAdd_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.moduleBuilder_tap, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_5.addWidget(self.line_8)
        self.data_label = QtWidgets.QLabel(Form)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.verticalLayout_5.addWidget(self.data_label)
        self.authour_label = QtWidgets.QLabel(Form)
        self.authour_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authour_label.setObjectName("authour_label")
        self.verticalLayout_5.addWidget(self.authour_label)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Form", "ReNamer", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Form", "# ReName = Name + Padding(**)", None, -1))
        self.name_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Name..", None, -1))
        self.padding_lineEdit.setText(QtWidgets.QApplication.translate("Form", "0", None, -1))
        self.rename_pushButton.setText(QtWidgets.QApplication.translate("Form", "ReName", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Form", "# Enter after entering", None, -1))
        self.prefix_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Prefix..", None, -1))
        self.suffix_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Suffix..", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Form", "# Old Name >> New Name", None, -1))
        self.oldname_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Old Name..", None, -1))
        self.newname_lineEdit.setText(QtWidgets.QApplication.translate("Form", "New Name..", None, -1))
        self.change_pushButton.setText(QtWidgets.QApplication.translate("Form", "ChangeName", None, -1))
        self.message_label.setText(QtWidgets.QApplication.translate("Form", "...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rename_tap), QtWidgets.QApplication.translate("Form", "rename", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Form", "Rig Support Tool", None, -1))
        self.baseName_lineEdit.setText(QtWidgets.QApplication.translate("Form", " Base Name entering..", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Linear Spacing Joint", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "# Select the top joints and set (default [xAxis, zUp])", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Spacing Number : ", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Form", "orientJoint : ", None, -1))
        self.oj_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "xzy", None, -1))
        self.oj_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "yxz", None, -1))
        self.oj_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "zyx", None, -1))
        self.oj_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "xyz", None, -1))
        self.oj_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "yzx", None, -1))
        self.oj_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "zxy", None, -1))
        self.sao_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "zup", None, -1))
        self.sao_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "yup", None, -1))
        self.sao_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "xup", None, -1))
        self.sao_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "zdown", None, -1))
        self.sao_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "ydown", None, -1))
        self.sao_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "xdown", None, -1))
        self.LSJoint_pushButton.setText(QtWidgets.QApplication.translate("Form", "Set", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Main Setting", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "# Select the top joint and build", None, -1))
        self.main_pushButton.setText(QtWidgets.QApplication.translate("Form", "Main FK / IK Build", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "Surface Parameter Space", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "# Select the surface and get", None, -1))
        self.paramSpace_pushButton.setText(QtWidgets.QApplication.translate("Form", "Get Space", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "Hybrid Setting", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "# Select the top joints and build", None, -1))
        self.hybrid_pushButton.setText(QtWidgets.QApplication.translate("Form", "Hybrid FK / IK Build", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Form", "Attach Setting", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Form", "# Select the curve and build", None, -1))
        self.objCV_pushButton.setText(QtWidgets.QApplication.translate("Form", "Object CV Curve", None, -1))
        self.crvNull_pushButton.setText(QtWidgets.QApplication.translate("Form", "Curve At Null", None, -1))
        self.attach_pushButton.setText(QtWidgets.QApplication.translate("Form", "Attach Build", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Form", "Switch Setting", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Form", "#  cape_switch.ma file import", None, -1))
        self.switchImport_pushButton.setText(QtWidgets.QApplication.translate("Form", "Import", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Form", "Curve Shape Change", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Form", "# Select[0] : Item / Select[1] : Target", None, -1))
        self.shapeChange_pushButton.setText(QtWidgets.QApplication.translate("Form", "Change", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rigSupport_tap), QtWidgets.QApplication.translate("Form", "rigSupport", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("Form", "Module Builder", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Form", "# If a fit file exists in the prefix name and path, it will be imported.", None, -1))
        self.M_prefix_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Prefix Name..", None, -1))
        self.module_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "spine", None, -1))
        self.module_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "leg", None, -1))
        self.module_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "arm", None, -1))
        self.module_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "neck", None, -1))
        self.module_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "head", None, -1))
        self.module_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "hand", None, -1))
        self.module_comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "foot", None, -1))
        self.module_comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "Qarm", None, -1))
        self.module_comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "Qleg", None, -1))
        self.module_comboBox.setItemText(9, QtWidgets.QApplication.translate("Form", "tail", None, -1))
        self.import_pushButton.setText(QtWidgets.QApplication.translate("Form", "Import", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("Form", "# Selection List [0] = Base Fit top group / Selection List [1] = Mirror Fit top group", None, -1))
        self.mirror_pushButton.setText(QtWidgets.QApplication.translate("Form", "Mirror", None, -1))
        self.build_pushButton.setText(QtWidgets.QApplication.translate("Form", "Build", None, -1))
        self.rebuild_pushButton.setText(QtWidgets.QApplication.translate("Form", "ReBuild", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Form", "Bend Setting", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Form", "# Execute after selecting the joint to be installed", None, -1))
        self.bendType_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "L", None, -1))
        self.bendType_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "R", None, -1))
        self.bendAdd_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("Form", "Module Parent", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Form", "# Selection List [0] = Parents Joint / Selection List [1] = Child top Group", None, -1))
        self.parent_pushButton.setText(QtWidgets.QApplication.translate("Form", "Parent", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("Form", "Follow Setting", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Form", "# Selection List [:-1] = Follower / Selection List [-1] = Following", None, -1))
        self.followEnum_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Enum Name..", None, -1))
        self.followAdd_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.moduleBuilder_tap), QtWidgets.QApplication.translate("Form", "moduleBuilder", None, -1))
        self.data_label.setText(QtWidgets.QApplication.translate("Form", "DATA : 20210706", None, -1))
        self.authour_label.setText(QtWidgets.QApplication.translate("Form", "AUTHOUR : Minsung", None, -1))