(dp1
S'info'
p2
VEnable the refresh of the viewport after disabling it
p3
sS'name'
p4
VEnable Viewport Refresh
p5
sS'tags'
p6
Vrefresh,viewport
p7
sS'syntax'
p8
S'python'
p9
sS'command'
p10
Vimport maya.cmds as cmds\u000amaya.mel.eval("paneLayout -e -manage true $gMainPane")
p11
sS'id'
p12
S'348a5a708afa02L'
p13
sS'icon'
p14
VenableViewportRefresh
p15
s.
