# -*- coding: utf-8 -*-
"""============================================================================
Module descriptions.
ConnectManager.ui conevert python file

__AUTHOR__ = 'minsung'
__UPDATE__ = 20210129

:Example:
import ConnectManagerForm
ui = ConnectManagerForm.Ui_MainWindow()

============================================================================"""
#
# when start coding 3 empty lines.
#
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ConnectManager_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gulim")
        self.ConnectManager_groupBox.setFont(font)
        self.ConnectManager_groupBox.setObjectName("ConnectManager_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.ConnectManager_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.mainverticalLayout = QtWidgets.QVBoxLayout()
        self.mainverticalLayout.setObjectName("mainverticalLayout")
        self.listhorizontalLayout = QtWidgets.QHBoxLayout()
        self.listhorizontalLayout.setObjectName("listhorizontalLayout")
        self.outlistverticalLayout = QtWidgets.QVBoxLayout()
        self.outlistverticalLayout.setObjectName("outlistverticalLayout")
        self.AlistWidget = QtWidgets.QListWidget(self.ConnectManager_groupBox)
        self.AlistWidget.setDragEnabled(True)
        self.AlistWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.AlistWidget.setAlternatingRowColors(True)
        self.AlistWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.AlistWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.AlistWidget.setObjectName("AlistWidget")
        self.outlistverticalLayout.addWidget(self.AlistWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AAddpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.AAddpushButton.setObjectName("AAddpushButton")
        self.horizontalLayout.addWidget(self.AAddpushButton)
        self.ARemovepushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.ARemovepushButton.setObjectName("ARemovepushButton")
        self.horizontalLayout.addWidget(self.ARemovepushButton)
        self.outlistverticalLayout.addLayout(self.horizontalLayout)
        self.listhorizontalLayout.addLayout(self.outlistverticalLayout)
        self.sortButtonverticalLayout = QtWidgets.QVBoxLayout()
        self.sortButtonverticalLayout.setObjectName("sortButtonverticalLayout")
        self.sortpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.sortpushButton.setFlat(True)
        self.sortpushButton.setObjectName("sortpushButton")
        self.sortButtonverticalLayout.addWidget(self.sortpushButton)
        self.reversepushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.reversepushButton.setFlat(True)
        self.reversepushButton.setObjectName("reversepushButton")
        self.sortButtonverticalLayout.addWidget(self.reversepushButton)
        self.pparentpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.pparentpushButton.setFlat(True)
        self.pparentpushButton.setObjectName("pparentpushButton")
        self.sortButtonverticalLayout.addWidget(self.pparentpushButton)
        self.listhorizontalLayout.addLayout(self.sortButtonverticalLayout)
        self.inlistverticalLayout = QtWidgets.QVBoxLayout()
        self.inlistverticalLayout.setObjectName("inlistverticalLayout")
        self.BlistWidget = QtWidgets.QListWidget(self.ConnectManager_groupBox)
        self.BlistWidget.setDragEnabled(True)
        self.BlistWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.BlistWidget.setAlternatingRowColors(True)
        self.BlistWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.BlistWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.BlistWidget.setObjectName("BlistWidget")
        self.inlistverticalLayout.addWidget(self.BlistWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BAddrpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.BAddrpushButton.setObjectName("BAddrpushButton")
        self.horizontalLayout_2.addWidget(self.BAddrpushButton)
        self.BRemovepushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.BRemovepushButton.setObjectName("BRemovepushButton")
        self.horizontalLayout_2.addWidget(self.BRemovepushButton)
        self.inlistverticalLayout.addLayout(self.horizontalLayout_2)
        self.listhorizontalLayout.addLayout(self.inlistverticalLayout)
        self.mainverticalLayout.addLayout(self.listhorizontalLayout)
        self.connectTypegroupBox = QtWidgets.QGroupBox(self.ConnectManager_groupBox)
        self.connectTypegroupBox.setTitle("")
        self.connectTypegroupBox.setFlat(False)
        self.connectTypegroupBox.setCheckable(False)
        self.connectTypegroupBox.setObjectName("connectTypegroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.connectTypegroupBox)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.connectTypehorizontalLayout = QtWidgets.QHBoxLayout()
        self.connectTypehorizontalLayout.setObjectName("connectTypehorizontalLayout")
        self.OneToNradioButton = QtWidgets.QRadioButton(self.connectTypegroupBox)
        self.OneToNradioButton.setObjectName("OneToNradioButton")
        self.connectTypehorizontalLayout.addWidget(self.OneToNradioButton)
        self.NToNradioButton = QtWidgets.QRadioButton(self.connectTypegroupBox)
        self.NToNradioButton.setChecked(True)
        self.NToNradioButton.setObjectName("NToNradioButton")
        self.connectTypehorizontalLayout.addWidget(self.NToNradioButton)
        self.gridLayout_2.addLayout(self.connectTypehorizontalLayout, 0, 0, 1, 1)
        self.mainverticalLayout.addWidget(self.connectTypegroupBox)
        self.attrrhorizontalLayout = QtWidgets.QHBoxLayout()
        self.attrrhorizontalLayout.setSpacing(6)
        self.attrrhorizontalLayout.setObjectName("attrrhorizontalLayout")
        self.outAttrlabel = QtWidgets.QLabel(self.ConnectManager_groupBox)
        self.outAttrlabel.setObjectName("outAttrlabel")
        self.attrrhorizontalLayout.addWidget(self.outAttrlabel)
        self.OutAttrtextEdit = QtWidgets.QTextEdit(self.ConnectManager_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutAttrtextEdit.sizePolicy().hasHeightForWidth())
        self.OutAttrtextEdit.setSizePolicy(sizePolicy)
        self.OutAttrtextEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.OutAttrtextEdit.setObjectName("OutAttrtextEdit")
        self.attrrhorizontalLayout.addWidget(self.OutAttrtextEdit)
        self.inAttrlabel = QtWidgets.QLabel(self.ConnectManager_groupBox)
        self.inAttrlabel.setObjectName("inAttrlabel")
        self.attrrhorizontalLayout.addWidget(self.inAttrlabel)
        self.InAttrtextEdit = QtWidgets.QTextEdit(self.ConnectManager_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InAttrtextEdit.sizePolicy().hasHeightForWidth())
        self.InAttrtextEdit.setSizePolicy(sizePolicy)
        self.InAttrtextEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.InAttrtextEdit.setObjectName("InAttrtextEdit")
        self.attrrhorizontalLayout.addWidget(self.InAttrtextEdit)
        self.connectpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.connectpushButton.setObjectName("connectpushButton")
        self.attrrhorizontalLayout.addWidget(self.connectpushButton)
        self.SetAttrpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.SetAttrpushButton.setObjectName("SetAttrpushButton")
        self.attrrhorizontalLayout.addWidget(self.SetAttrpushButton)
        self.mainverticalLayout.addLayout(self.attrrhorizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.ConnectManager_groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.mainverticalLayout.addWidget(self.line_3)
        self.constrainthorizontalLayout = QtWidgets.QHBoxLayout()
        self.constrainthorizontalLayout.setObjectName("constrainthorizontalLayout")
        self.constTypegroupBox = QtWidgets.QGroupBox(self.ConnectManager_groupBox)
        self.constTypegroupBox.setTitle("")
        self.constTypegroupBox.setObjectName("constTypegroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.constTypegroupBox)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.constTypehorizontalLayout = QtWidgets.QHBoxLayout()
        self.constTypehorizontalLayout.setObjectName("constTypehorizontalLayout")
        self.parentradioButton = QtWidgets.QRadioButton(self.constTypegroupBox)
        self.parentradioButton.setChecked(True)
        self.parentradioButton.setObjectName("parentradioButton")
        self.constTypehorizontalLayout.addWidget(self.parentradioButton)
        self.pointradioButton = QtWidgets.QRadioButton(self.constTypegroupBox)
        self.pointradioButton.setObjectName("pointradioButton")
        self.constTypehorizontalLayout.addWidget(self.pointradioButton)
        self.orientradioButton = QtWidgets.QRadioButton(self.constTypegroupBox)
        self.orientradioButton.setObjectName("orientradioButton")
        self.constTypehorizontalLayout.addWidget(self.orientradioButton)
        self.scaleradioButton = QtWidgets.QRadioButton(self.constTypegroupBox)
        self.scaleradioButton.setObjectName("scaleradioButton")
        self.constTypehorizontalLayout.addWidget(self.scaleradioButton)
        self.gridLayout_3.addLayout(self.constTypehorizontalLayout, 0, 0, 1, 1)
        self.constrainthorizontalLayout.addWidget(self.constTypegroupBox)
        self.maintaincheckBox = QtWidgets.QCheckBox(self.ConnectManager_groupBox)
        self.maintaincheckBox.setChecked(True)
        self.maintaincheckBox.setObjectName("maintaincheckBox")
        self.constrainthorizontalLayout.addWidget(self.maintaincheckBox)
        self.constraintpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.constraintpushButton.setObjectName("constraintpushButton")
        self.constrainthorizontalLayout.addWidget(self.constraintpushButton)
        self.mainverticalLayout.addLayout(self.constrainthorizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.ConnectManager_groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.mainverticalLayout.addWidget(self.line_4)
        self.mirrorhorizontalLayout = QtWidgets.QHBoxLayout()
        self.mirrorhorizontalLayout.setObjectName("mirrorhorizontalLayout")
        self.mirrorTypehorizontalLayout = QtWidgets.QHBoxLayout()
        self.mirrorTypehorizontalLayout.setObjectName("mirrorTypehorizontalLayout")
        self.mirrorReversgroupBox = QtWidgets.QGroupBox(self.ConnectManager_groupBox)
        self.mirrorReversgroupBox.setTitle("")
        self.mirrorReversgroupBox.setObjectName("mirrorReversgroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.mirrorReversgroupBox)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mirrorRevershorizontalLayout = QtWidgets.QHBoxLayout()
        self.mirrorRevershorizontalLayout.setObjectName("mirrorRevershorizontalLayout")
        self.axisYZradioButton = QtWidgets.QRadioButton(self.mirrorReversgroupBox)
        self.axisYZradioButton.setChecked(True)
        self.axisYZradioButton.setObjectName("axisYZradioButton")
        self.mirrorRevershorizontalLayout.addWidget(self.axisYZradioButton)
        self.axisXYradioButton = QtWidgets.QRadioButton(self.mirrorReversgroupBox)
        self.axisXYradioButton.setObjectName("axisXYradioButton")
        self.mirrorRevershorizontalLayout.addWidget(self.axisXYradioButton)
        self.axisZXradioButton = QtWidgets.QRadioButton(self.mirrorReversgroupBox)
        self.axisZXradioButton.setObjectName("axisZXradioButton")
        self.mirrorRevershorizontalLayout.addWidget(self.axisZXradioButton)
        self.gridLayout_4.addLayout(self.mirrorRevershorizontalLayout, 0, 0, 1, 1)
        self.mirrorTypehorizontalLayout.addWidget(self.mirrorReversgroupBox)
        self.mirrorhorizontalLayout.addLayout(self.mirrorTypehorizontalLayout)
        self.mirrorpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.mirrorpushButton.setObjectName("mirrorpushButton")
        self.mirrorhorizontalLayout.addWidget(self.mirrorpushButton)
        self.mainverticalLayout.addLayout(self.mirrorhorizontalLayout)
        self.line_5 = QtWidgets.QFrame(self.ConnectManager_groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.mainverticalLayout.addWidget(self.line_5)
        self.wrapTranshorizontalLayout = QtWidgets.QHBoxLayout()
        self.wrapTranshorizontalLayout.setObjectName("wrapTranshorizontalLayout")
        self.wrappushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.wrappushButton.setObjectName("wrappushButton")
        self.wrapTranshorizontalLayout.addWidget(self.wrappushButton)
        self.transformrpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.transformrpushButton.setObjectName("transformrpushButton")
        self.wrapTranshorizontalLayout.addWidget(self.transformrpushButton)
        self.SkinBindpushButton = QtWidgets.QPushButton(self.ConnectManager_groupBox)
        self.SkinBindpushButton.setObjectName("SkinBindpushButton")
        self.wrapTranshorizontalLayout.addWidget(self.SkinBindpushButton)
        self.mainverticalLayout.addLayout(self.wrapTranshorizontalLayout)
        self.gridLayout.addLayout(self.mainverticalLayout, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.ConnectManager_groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.ConnectManager_groupBox)
        font = QtGui.QFont()
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.ConnectManager_groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.ConnectManager_groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "ConnectManager_V01", None, -1))
        self.AAddpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "add Item", None, -1))
        self.ARemovepushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.sortpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Sort", None, -1))
        self.reversepushButton.setText(QtWidgets.QApplication.translate("MainWindow", "<>", None, -1))
        self.pparentpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "PParent", None, -1))
        self.BAddrpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "add Item", None, -1))
        self.BRemovepushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Remove", None, -1))
        self.OneToNradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "One To N", None, -1))
        self.NToNradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "N to N", None, -1))
        self.outAttrlabel.setText(QtWidgets.QApplication.translate("MainWindow", "OutAttr : ", None, -1))
        self.inAttrlabel.setText(QtWidgets.QApplication.translate("MainWindow", "InAttr : ", None, -1))
        self.connectpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.SetAttrpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "SetAttr", None, -1))
        self.parentradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Parent", None, -1))
        self.pointradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Point", None, -1))
        self.orientradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Orient", None, -1))
        self.scaleradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "Scale", None, -1))
        self.maintaincheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "MainTain", None, -1))
        self.constraintpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Constraint", None, -1))
        self.axisYZradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "AxisYZ", None, -1))
        self.axisXYradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "AxisXY", None, -1))
        self.axisZXradioButton.setText(QtWidgets.QApplication.translate("MainWindow", "AxisZX", None, -1))
        self.mirrorpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Mirror", None, -1))
        self.wrappushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Wrap", None, -1))
        self.transformrpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Transform", None, -1))
        self.SkinBindpushButton.setText(QtWidgets.QApplication.translate("MainWindow", "SkinBind", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "AUTHOR : SUNGSEO", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "UPDATE : 20210208", None, -1))