from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(476, 477)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.prefix_lineEdit = QtWidgets.QLineEdit(Form)
        self.prefix_lineEdit.setObjectName("prefix_lineEdit")
        self.verticalLayout.addWidget(self.prefix_lineEdit)
        self.module_comboBox = QtWidgets.QComboBox(Form)
        self.module_comboBox.setObjectName("module_comboBox")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.module_comboBox.addItem("")
        self.verticalLayout.addWidget(self.module_comboBox)
        self.import_pushButton = QtWidgets.QPushButton(Form)
        self.import_pushButton.setObjectName("import_pushButton")
        self.verticalLayout.addWidget(self.import_pushButton)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.mirror_pushButton = QtWidgets.QPushButton(Form)
        self.mirror_pushButton.setObjectName("mirror_pushButton")
        self.verticalLayout.addWidget(self.mirror_pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.build_pushButton = QtWidgets.QPushButton(Form)
        self.build_pushButton.setObjectName("build_pushButton")
        self.horizontalLayout.addWidget(self.build_pushButton)
        self.rebuild_pushButton = QtWidgets.QPushButton(Form)
        self.rebuild_pushButton.setObjectName("rebuild_pushButton")
        self.horizontalLayout.addWidget(self.rebuild_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bendType_comboBox = QtWidgets.QComboBox(Form)
        self.bendType_comboBox.setObjectName("bendType_comboBox")
        self.bendType_comboBox.addItem("")
        self.bendType_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.bendType_comboBox)
        self.bendAdd_pushButton = QtWidgets.QPushButton(Form)
        self.bendAdd_pushButton.setObjectName("bendAdd_pushButton")
        self.horizontalLayout_2.addWidget(self.bendAdd_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.parent_pushButton = QtWidgets.QPushButton(Form)
        self.parent_pushButton.setObjectName("parent_pushButton")
        self.verticalLayout.addWidget(self.parent_pushButton)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.followEnum_lineEdit = QtWidgets.QLineEdit(Form)
        self.followEnum_lineEdit.setObjectName("followEnum_lineEdit")
        self.horizontalLayout_3.addWidget(self.followEnum_lineEdit)
        self.followAdd_pushButton = QtWidgets.QPushButton(Form)
        self.followAdd_pushButton.setObjectName("followAdd_pushButton")
        self.horizontalLayout_3.addWidget(self.followAdd_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.data_label = QtWidgets.QLabel(Form)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.verticalLayout.addWidget(self.data_label)
        self.authour_label = QtWidgets.QLabel(Form)
        self.authour_label.setAlignment(QtCore.Qt.AlignCenter)
        self.authour_label.setObjectName("authour_label")
        self.verticalLayout.addWidget(self.authour_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Module Builder", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Form", "# If a fit file exists in the prefix name and path, it will be imported.", None, -1))
        self.prefix_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Prefix Name..", None, -1))
        self.module_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "spine", None, -1))
        self.module_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "leg", None, -1))
        self.module_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "arm", None, -1))
        self.module_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "neck", None, -1))
        self.module_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "head", None, -1))
        self.module_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "hand", None, -1))
        self.module_comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "foot", None, -1))
        self.module_comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "Qarm", None, -1))
        self.module_comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "Qleg", None, -1))
        self.module_comboBox.setItemText(9, QtWidgets.QApplication.translate("Form", "tail", None, -1))
        self.import_pushButton.setText(QtWidgets.QApplication.translate("Form", "Import", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "# Selection List [0] = Base Fit top group / Selection List [1] = Mirror Fit top group", None, -1))
        self.mirror_pushButton.setText(QtWidgets.QApplication.translate("Form", "Mirror", None, -1))
        self.build_pushButton.setText(QtWidgets.QApplication.translate("Form", "Build", None, -1))
        self.rebuild_pushButton.setText(QtWidgets.QApplication.translate("Form", "ReBuild", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Bend Setting", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Form", "# Execute after selecting the joint to be installed", None, -1))
        self.bendType_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "L", None, -1))
        self.bendType_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "R", None, -1))
        self.bendAdd_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Module Parent", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "# Selection List [0] = Parents Joint / Selection List [1] = Child top Group", None, -1))
        self.parent_pushButton.setText(QtWidgets.QApplication.translate("Form", "Parent", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "Follow Setting", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "# Selection List [:-1] = Follower / Selection List [-1] = Following", None, -1))
        self.followEnum_lineEdit.setText(QtWidgets.QApplication.translate("Form", "Enum Name..", None, -1))
        self.followAdd_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add", None, -1))
        self.data_label.setText(QtWidgets.QApplication.translate("Form", "DATA : 20210705", None, -1))
        self.authour_label.setText(QtWidgets.QApplication.translate("Form", "AUTHOUR : Minsung", None, -1))