from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(471, 724)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fitRef_label = QtWidgets.QLabel(Form)
        self.fitRef_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.fitRef_label.setObjectName("fitRef_label")
        self.verticalLayout_2.addWidget(self.fitRef_label)
        self.fitRef_comboBox = QtWidgets.QComboBox(Form)
        self.fitRef_comboBox.setObjectName("fitRef_comboBox")
        self.verticalLayout_2.addWidget(self.fitRef_comboBox)
        self.fitRef_pushButton = QtWidgets.QPushButton(Form)
        self.fitRef_pushButton.setObjectName("fitRef_pushButton")
        self.verticalLayout_2.addWidget(self.fitRef_pushButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fitPrt_label = QtWidgets.QLabel(Form)
        self.fitPrt_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.fitPrt_label.setObjectName("fitPrt_label")
        self.verticalLayout_3.addWidget(self.fitPrt_label)
        self.fitPrt_comboBox = QtWidgets.QComboBox(Form)
        self.fitPrt_comboBox.setObjectName("fitPrt_comboBox")
        self.verticalLayout_3.addWidget(self.fitPrt_comboBox)
        self.prefix_textEdit = QtWidgets.QLineEdit(Form)
        self.prefix_textEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.prefix_textEdit.setObjectName("prefix_textEdit")
        self.verticalLayout_3.addWidget(self.prefix_textEdit)
        self.addParts_pushButton = QtWidgets.QPushButton(Form)
        self.addParts_pushButton.setObjectName("addParts_pushButton")
        self.verticalLayout_3.addWidget(self.addParts_pushButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Parts_treeWidget = QtWidgets.QTreeWidget(Form)
        self.Parts_treeWidget.setDragEnabled(True)
        self.Parts_treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.Parts_treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Parts_treeWidget.setObjectName("Parts_treeWidget")
        self.Parts_treeWidget.header().setDefaultSectionSize(100)
        self.horizontalLayout_4.addWidget(self.Parts_treeWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.referencePath_label = QtWidgets.QLabel(Form)
        self.referencePath_label.setObjectName("referencePath_label")
        self.verticalLayout_5.addWidget(self.referencePath_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bendy_label = QtWidgets.QLabel(Form)
        self.bendy_label.setObjectName("bendy_label")
        self.horizontalLayout_3.addWidget(self.bendy_label)
        self.bendyIndex_spinBox = QtWidgets.QSpinBox(Form)
        self.bendyIndex_spinBox.setObjectName("bendyIndex_spinBox")
        self.horizontalLayout_3.addWidget(self.bendyIndex_spinBox)
        self.bendy_pushButton = QtWidgets.QPushButton(Form)
        self.bendy_pushButton.setObjectName("bendy_pushButton")
        self.horizontalLayout_3.addWidget(self.bendy_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prefix_label = QtWidgets.QLabel(Form)
        self.prefix_label.setObjectName("prefix_label")
        self.horizontalLayout.addWidget(self.prefix_label)
        self.prefixLabel_comboBox = QtWidgets.QComboBox(Form)
        self.prefixLabel_comboBox.setEditable(True)
        self.prefixLabel_comboBox.setObjectName("prefixLabel_comboBox")
        self.prefixLabel_comboBox.addItem("")
        self.prefixLabel_comboBox.addItem("")
        self.prefixLabel_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.prefixLabel_comboBox)
        self.Label_pushButton = QtWidgets.QPushButton(Form)
        self.Label_pushButton.setObjectName("Label_pushButton")
        self.horizontalLayout.addWidget(self.Label_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.follow_label = QtWidgets.QLabel(Form)
        self.follow_label.setObjectName("follow_label")
        self.verticalLayout_4.addWidget(self.follow_label)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.mirror_pushButton = QtWidgets.QPushButton(Form)
        self.mirror_pushButton.setObjectName("mirror_pushButton")
        self.verticalLayout_4.addWidget(self.mirror_pushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.clear_pushButton = QtWidgets.QPushButton(Form)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.verticalLayout_3.addWidget(self.clear_pushButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.build_label = QtWidgets.QLabel(Form)
        self.build_label.setAlignment(QtCore.Qt.AlignCenter)
        self.build_label.setObjectName("build_label")
        self.verticalLayout.addWidget(self.build_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EditMode_pushButton = QtWidgets.QPushButton(Form)
        self.EditMode_pushButton.setObjectName("EditMode_pushButton")
        self.horizontalLayout_2.addWidget(self.EditMode_pushButton)
        self.build_pushButton = QtWidgets.QPushButton(Form)
        self.build_pushButton.setObjectName("build_pushButton")
        self.horizontalLayout_2.addWidget(self.build_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.fitRef_label.setText(QtWidgets.QApplication.translate("Form", "__Fit Reference__", None, -1))
        self.fitRef_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add Reference", None, -1))
        self.fitPrt_label.setText(QtWidgets.QApplication.translate("Form", "__Fit Parts__", None, -1))
        self.prefix_textEdit.setText(QtWidgets.QApplication.translate("Form", "Base Name", None, -1))
        self.addParts_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add Parts", None, -1))
        self.Parts_treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("Form", "Tree Structure", None, -1))
        self.referencePath_label.setText(QtWidgets.QApplication.translate("Form", "Reference File Path", None, -1))
        self.bendy_label.setText(QtWidgets.QApplication.translate("Form", "Bendy Index", None, -1))
        self.bendy_pushButton.setText(QtWidgets.QApplication.translate("Form", "Set", None, -1))
        self.prefix_label.setText(QtWidgets.QApplication.translate("Form", "Label", None, -1))
        self.prefixLabel_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "L", None, -1))
        self.prefixLabel_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "R", None, -1))
        self.prefixLabel_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "M", None, -1))
        self.Label_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add", None, -1))
        self.follow_label.setText(QtWidgets.QApplication.translate("Form", "Follow", None, -1))
        self.mirror_pushButton.setText(QtWidgets.QApplication.translate("Form", "Mirror", None, -1))
        self.clear_pushButton.setText(QtWidgets.QApplication.translate("Form", "Clear", None, -1))
        self.build_label.setText(QtWidgets.QApplication.translate("Form", "__Build__", None, -1))
        self.EditMode_pushButton.setText(QtWidgets.QApplication.translate("Form", "EditMode", None, -1))
        self.build_pushButton.setText(QtWidgets.QApplication.translate("Form", "Build", None, -1))