from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fitRef_label = QtWidgets.QLabel(Form)
        self.fitRef_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.fitRef_label.setObjectName("fitRef_label")
        self.verticalLayout_2.addWidget(self.fitRef_label)
        self.fitRef_comboBox = QtWidgets.QComboBox(Form)
        self.fitRef_comboBox.setObjectName("fitRef_comboBox")
        self.verticalLayout_2.addWidget(self.fitRef_comboBox)
        self.fitRef_pushButton = QtWidgets.QPushButton(Form)
        self.fitRef_pushButton.setObjectName("fitRef_pushButton")
        self.verticalLayout_2.addWidget(self.fitRef_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fitPrt_label = QtWidgets.QLabel(Form)
        self.fitPrt_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.fitPrt_label.setObjectName("fitPrt_label")
        self.verticalLayout_3.addWidget(self.fitPrt_label)
        self.fitPrt_comboBox = QtWidgets.QComboBox(Form)
        self.fitPrt_comboBox.setObjectName("fitPrt_comboBox")
        self.verticalLayout_3.addWidget(self.fitPrt_comboBox)
        self.prefix_lineEdit = QtWidgets.QLineEdit(Form)
        self.prefix_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.prefix_lineEdit.setObjectName("prefix_lineEdit")
        self.verticalLayout_3.addWidget(self.prefix_lineEdit)
        self.addParts_pushButton = QtWidgets.QPushButton(Form)
        self.addParts_pushButton.setObjectName("addParts_pushButton")
        self.verticalLayout_3.addWidget(self.addParts_pushButton)
        self.Parts_treeWidget = QtWidgets.QTreeWidget(Form)
        self.Parts_treeWidget.setObjectName("Parts_treeWidget")
        self.Parts_treeWidget.header().setDefaultSectionSize(100)
        self.verticalLayout_3.addWidget(self.Parts_treeWidget)
        self.clear_pushButton = QtWidgets.QPushButton(Form)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.verticalLayout_3.addWidget(self.clear_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.build_label = QtWidgets.QLabel(Form)
        self.build_label.setAlignment(QtCore.Qt.AlignCenter)
        self.build_label.setObjectName("build_label")
        self.verticalLayout.addWidget(self.build_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EditMode_pushButton = QtWidgets.QPushButton(Form)
        self.EditMode_pushButton.setObjectName("EditMode_pushButton")
        self.horizontalLayout_2.addWidget(self.EditMode_pushButton)
        self.build_pushButton = QtWidgets.QPushButton(Form)
        self.build_pushButton.setObjectName("build_pushButton")
        self.horizontalLayout_2.addWidget(self.build_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.fitRef_label.setText(QtWidgets.QApplication.translate("Form", "__Fit Reference__", None, -1))
        self.fitRef_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add Reference", None, -1))
        self.fitPrt_label.setText(QtWidgets.QApplication.translate("Form", "__Fit Parts__", None, -1))
        self.prefix_lineEdit.setText(QtWidgets.QApplication.translate("Form", "\" Insert Prefix Name \"", None, -1))
        self.addParts_pushButton.setText(QtWidgets.QApplication.translate("Form", "Add Parts", None, -1))
        self.Parts_treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("Form", "Preoperties", None, -1))
        self.Parts_treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("Form", "Value", None, -1))
        self.clear_pushButton.setText(QtWidgets.QApplication.translate("Form", "Clear", None, -1))
        self.build_label.setText(QtWidgets.QApplication.translate("Form", "__Build__", None, -1))
        self.EditMode_pushButton.setText(QtWidgets.QApplication.translate("Form", "EditMode", None, -1))
        self.build_pushButton.setText(QtWidgets.QApplication.translate("Form", "Build", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "AUTHOR = SungSeo", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "UPDATE = 20210501", None, -1))