import maya.cmds as cmds
cmds.spaceLocator(n = 'FK_arm_R_loc', p = (0, 0, 0))
cmds.setAttr('FK_arm_R_loc.rotate', 90, 0, -180, type="double3")
cmds.spaceLocator(n = 'FK_arm_L_loc', p = (0, 0, 0))
cmds.setAttr('FK_arm_L_loc.rotate', -90, 0, 180, type="double3")
cmds.spaceLocator(n = 'FK_leg_R_loc', p = (0, 0, 0))
cmds.setAttr('FK_leg_R_loc.rotate', 90, 0, -90, type="double3")
cmds.spaceLocator(n = 'FK_leg_L_loc', p = (0, 0, 0))
cmds.setAttr('FK_leg_L_loc.rotate', -90, 0, 90, type="double3")
cmds.setAttr ('FKIKLeg_R.FKIKBlend', 0)
cmds.setAttr ('FKIKArm_R.FKIKBlend', 0)
cmds.setAttr ('FKIKArm_L.FKIKBlend', 0)
cmds.setAttr ('FKIKSpine_M.FKIKBlend', 0)
cmds.setAttr ('FKIKLeg_L.FKIKBlend', 0)
cmds.matchTransform('FKScapula_R', 'FKShoulder_R', 'FKElbow_R', 'FKWrist_R', 'FK_arm_R_loc', rot = True)
cmds.matchTransform('FKScapula_L', 'FKShoulder_L', 'FKElbow_L', 'FKWrist_L', 'FK_arm_L_loc', rot = True)
cmds.matchTransform('FKHip_R', 'FKKnee_R', 'FKAnkle_R', 'FK_leg_R_loc', rot = True)
cmds.matchTransform('FKHip_L', 'FKKnee_L', 'FKAnkle_L', 'FK_leg_L_loc', rot = True)
cmds.delete('FK_arm_R_loc', 'FK_arm_L_loc', 'FK_leg_R_loc', 'FK_leg_L_loc')