from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(226, 456)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.templateToolBox = QtWidgets.QToolBox(Form)
        self.templateToolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.templateToolBox.setLineWidth(0)
        self.templateToolBox.setObjectName("templateToolBox")
        self.fitSkeleton_page = QtWidgets.QWidget()
        self.fitSkeleton_page.setGeometry(QtCore.QRect(0, 0, 208, 210))
        self.fitSkeleton_page.setObjectName("fitSkeleton_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fitSkeleton_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.temp_listWidget = QtWidgets.QListWidget(self.fitSkeleton_page)
        self.temp_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.temp_listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.temp_listWidget.setLineWidth(0)
        self.temp_listWidget.setDragEnabled(True)
        self.temp_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.temp_listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.temp_listWidget.setAlternatingRowColors(False)
        self.temp_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.temp_listWidget.setObjectName("temp_listWidget")
        self.gridLayout_2.addWidget(self.temp_listWidget, 0, 0, 1, 1)
        self.templateToolBox.addItem(self.fitSkeleton_page, "")
        self.partsSkeleton_page = QtWidgets.QWidget()
        self.partsSkeleton_page.setGeometry(QtCore.QRect(0, 0, 208, 210))
        self.partsSkeleton_page.setObjectName("partsSkeleton_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.partsSkeleton_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.parts_listWidget = QtWidgets.QListWidget(self.partsSkeleton_page)
        self.parts_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.parts_listWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.parts_listWidget.setLineWidth(0)
        self.parts_listWidget.setDragEnabled(True)
        self.parts_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.parts_listWidget.setAlternatingRowColors(False)
        self.parts_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.parts_listWidget.setObjectName("parts_listWidget")
        self.gridLayout_3.addWidget(self.parts_listWidget, 0, 0, 1, 1)
        self.templateToolBox.addItem(self.partsSkeleton_page, "")
        self.gridLayout.addWidget(self.templateToolBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.templateToolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.templateToolBox.setItemText(self.templateToolBox.indexOf(self.fitSkeleton_page), QtWidgets.QApplication.translate("Form", "Template Skeleton", None, -1))
        self.templateToolBox.setItemText(self.templateToolBox.indexOf(self.partsSkeleton_page), QtWidgets.QApplication.translate("Form", "Parts Skeleton", None, -1))