(dp1
Vinfo
p2
V\ud074\ub7ec\uc2a4\ud130 \uc6e8\uc774\ud2b8 \ubcf5\uc0ac \ud234
p3
sVname
p4
VCopyWeightCluster
p5
sVtags
p6
Vtools
p7
sVsyntax
p8
Vpython
p9
sVcommand
p10
Vfrom deliver import CopyWeightClusterTool\u000areload(CopyWeightClusterTool)
p11
sVid
p12
S'3a73c8f776a7a0L'
p13
sVicon
p14
V
s.