(dp0
Vinfo
p1
Vjoint labeling / joint orient / joint insert
p2
sVname
p3
VjointSet
p4
sVtags
p5
Vtools
p6
sVsyntax
p7
Vpython
p8
sVcommand
p9
Vfrom ui.deliver import jointSet\u000atry:\u000a    from imp import *\u000aexcept:\u000a    pass\u000areload(jointSet)\u000a
p10
sVid
p11
V3a9f7f9079c362L
p12
sVicon
p13
V
p14
s.