(dp0
Vid
p1
V3d4b59e3b5f5c8
p2
sVname
p3
Vmrig
p4
sVinfo
p5
Vtool
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vfrom rigSupport.ui.convert import mRigTool\u000atry:\u000a    from imp import *\u000aexcept:\u000a    pass\u000areload(mRigTool)
p12
sVsyntax
p13
Vpython
p14
s.