(dp0
Vinfo
p1
Vrig support tool
p2
sVname
p3
VMRigTool
p4
sVtags
p5
Vtools
p6
sVsyntax
p7
Vpython
p8
sVcommand
p9
Vfrom rigSupport.ui.convert import mRigTool\u000atry:\u000a    from imp import *\u000aexcept:\u000a    pass\u000areload(mRigTool)\u000a
p10
sVid
p11
V3a72fd2e930f20L
p12
sVicon
p13
V
p14
s.