(dp1
Vinfo
p2
Vrig support tool
p3
sVname
p4
VMRigTool
p5
sVtags
p6
Vtools
p7
sVsyntax
p8
Vpython
p9
sVcommand
p10
Vfrom rigSupport.ui.convert import mRigTool\u000atry:\u000a    from imp import *\u000aexcept:\u000a    pass\u000areload(mRigTool)\u000a
p11
sVid
p12
S'3a72fd2e930f20L'
p13
sVicon
p14
V
s.
