(dp1
Vinfo
p2
V\uc120\ud0dd\ud55c \uc624\ube0c\uc81d\ud2b8 \uc0c1\uc704\uc5d0 Offset\uadf8\ub8f9\uc744 \ub9cc\ub4e4\uc5b4\uc90c.
p3
sVname
p4
VOffsetGrp
p5
sVtags
p6
Vscript
p7
sVsyntax
p8
Vpython
p9
sVcommand
p10
Vfrom rigSupport.lib import offsetGroup\u000areload(offsetGroup)
p11
sVid
p12
S'3a72ff1754d302L'
p13
sVicon
p14
V
s.