(dp1
Vinfo
p2
VposeReader setup
p3
sVname
p4
VposeReader
p5
sVtags
p6
Vtools
p7
sVsyntax
p8
Vpython
p9
sVcommand
p10
Vfrom ui.convert import poseReaderV01\u000areload(poseReaderV01)
p11
sVid
p12
S'3a9f814bee6410L'
p13
sVicon
p14
V
s.