(dp0
Vinfo
p1
VposeReader setup
p2
sVname
p3
VposeReader
p4
sVtags
p5
Vtools
p6
sVsyntax
p7
Vpython
p8
sVcommand
p9
Vfrom ui.convert import poseReaderV01\u000a\u000atry:\u000a    from imp import *\u000aexcept:\u000a    pass\u000a\u000areload(poseReaderV01)
p10
sVid
p11
V3a9f814bee6410L
p12
sVicon
p13
V
p14
s.