(dp0
Vid
p1
V3d4ab03fd71852
p2
sVname
p3
VreNamer
p4
sVinfo
p5
Vrename tool
p6
sVtags
p7
Vtools
p8
sVicon
p9
V
p10
sVcommand
p11
Vfrom rigSupport.ui.deliver import reNamer\u000aimport reNamer\u000atry:\u000a    from imp import *\u000aexcept:\u000a    pass\u000areload(reNamer)
p12
sVsyntax
p13
Vpython
p14
s.