from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Build_tab = QtWidgets.QWidget()
        self.Build_tab.setObjectName("Build_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Build_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.FitP_TWG = QtWidgets.QTreeWidget(self.Build_tab)
        self.FitP_TWG.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FitP_TWG.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FitP_TWG.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.FitP_TWG.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.FitP_TWG.setDragEnabled(True)
        self.FitP_TWG.setAlternatingRowColors(False)
        self.FitP_TWG.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.FitP_TWG.setIndentation(20)
        self.FitP_TWG.setWordWrap(False)
        self.FitP_TWG.setColumnCount(3)
        self.FitP_TWG.setObjectName("FitP_TWG")
        self.FitP_TWG.header().setVisible(True)
        self.FitP_TWG.header().setCascadingSectionResizes(True)
        self.FitP_TWG.header().setDefaultSectionSize(60)
        self.FitP_TWG.header().setHighlightSections(True)
        self.FitP_TWG.header().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.FitP_TWG, 16, 0, 1, 1)
        self.FitR_CBB = QtWidgets.QComboBox(self.Build_tab)
        self.FitR_CBB.setEnabled(True)
        self.FitR_CBB.setEditable(False)
        self.FitR_CBB.setCurrentText("")
        self.FitR_CBB.setObjectName("FitR_CBB")
        self.gridLayout.addWidget(self.FitR_CBB, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.Build_tab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 30, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.Build_tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 13, 0, 1, 1)
        self.FitP_CBB = QtWidgets.QComboBox(self.Build_tab)
        self.FitP_CBB.setEditable(False)
        self.FitP_CBB.setCurrentText("")
        self.FitP_CBB.setObjectName("FitP_CBB")
        self.gridLayout.addWidget(self.FitP_CBB, 14, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.Build_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 22, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.Build_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 11, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.BuildBT = QtWidgets.QPushButton(self.Build_tab)
        self.BuildBT.setObjectName("BuildBT")
        self.horizontalLayout_6.addWidget(self.BuildBT)
        self.EditModeBT = QtWidgets.QPushButton(self.Build_tab)
        self.EditModeBT.setObjectName("EditModeBT")
        self.horizontalLayout_6.addWidget(self.EditModeBT)
        self.gridLayout.addLayout(self.horizontalLayout_6, 31, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Build_tab)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.FitP_AddBT = QtWidgets.QPushButton(self.Build_tab)
        self.FitP_AddBT.setObjectName("FitP_AddBT")
        self.gridLayout.addWidget(self.FitP_AddBT, 15, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 1)
        self.FitR_AddBT = QtWidgets.QPushButton(self.Build_tab)
        self.FitR_AddBT.setObjectName("FitR_AddBT")
        self.gridLayout.addWidget(self.FitR_AddBT, 9, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.Build_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.BaseNametextEdit = QtWidgets.QTextEdit(self.Build_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaseNametextEdit.sizePolicy().hasHeightForWidth())
        self.BaseNametextEdit.setSizePolicy(sizePolicy)
        self.BaseNametextEdit.setMinimumSize(QtCore.QSize(0, 9))
        self.BaseNametextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BaseNametextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.BaseNametextEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.BaseNametextEdit.setTabStopWidth(80)
        self.BaseNametextEdit.setObjectName("BaseNametextEdit")
        self.horizontalLayout_2.addWidget(self.BaseNametextEdit)
        self.Name_EditBT = QtWidgets.QPushButton(self.Build_tab)
        self.Name_EditBT.setObjectName("Name_EditBT")
        self.horizontalLayout_2.addWidget(self.Name_EditBT)
        self.gridLayout.addLayout(self.horizontalLayout_2, 18, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 29, 0, 1, 1)
        self.ClearBT = QtWidgets.QPushButton(self.Build_tab)
        self.ClearBT.setObjectName("ClearBT")
        self.gridLayout.addWidget(self.ClearBT, 19, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.Build_tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Build_tab)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Build_tab, "")
        self.Sub_tab = QtWidgets.QWidget()
        self.Sub_tab.setObjectName("Sub_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Sub_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.Sub_tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.AtcMorror_RBT = QtWidgets.QRadioButton(self.Sub_tab)
        self.AtcMorror_RBT.setObjectName("AtcMorror_RBT")
        self.verticalLayout_3.addWidget(self.AtcMorror_RBT)
        self.Atc_CreateBT = QtWidgets.QPushButton(self.Sub_tab)
        self.Atc_CreateBT.setObjectName("Atc_CreateBT")
        self.verticalLayout_3.addWidget(self.Atc_CreateBT)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.Sub_tab)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.BindSkinBT = QtWidgets.QPushButton(self.Sub_tab)
        self.BindSkinBT.setObjectName("BindSkinBT")
        self.verticalLayout.addWidget(self.BindSkinBT)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.Sub_tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Proxy_CreateBT = QtWidgets.QPushButton(self.Sub_tab)
        self.Proxy_CreateBT.setObjectName("Proxy_CreateBT")
        self.gridLayout_4.addWidget(self.Proxy_CreateBT, 0, 0, 1, 1)
        self.Proxy_DeleteBT = QtWidgets.QPushButton(self.Sub_tab)
        self.Proxy_DeleteBT.setObjectName("Proxy_DeleteBT")
        self.gridLayout_4.addWidget(self.Proxy_DeleteBT, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Sub_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.Sub_tab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.FitR_CBB.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.FitP_TWG.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Label", None, -1))
        self.FitP_TWG.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Parts", None, -1))
        self.FitP_TWG.headerItem().setText(2, QtWidgets.QApplication.translate("MainWindow", "Discription", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "____Build____", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "____Fit Parts____", None, -1))
        self.BuildBT.setText(QtWidgets.QApplication.translate("MainWindow", "Build", None, -1))
        self.EditModeBT.setText(QtWidgets.QApplication.translate("MainWindow", "EditMode", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "____Fit Reference____", None, -1))
        self.FitP_AddBT.setText(QtWidgets.QApplication.translate("MainWindow", "Add Parts", None, -1))
        self.FitR_AddBT.setText(QtWidgets.QApplication.translate("MainWindow", "Add Reference", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Base Name", None, -1))
        self.Name_EditBT.setText(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.ClearBT.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "AUTHOR : SUNGSEO", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "UPDATE : 20210415", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Build_tab), QtWidgets.QApplication.translate("MainWindow", "Build", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "____Attach Control____", None, -1))
        self.AtcMorror_RBT.setText(QtWidgets.QApplication.translate("MainWindow", "Mirror", None, -1))
        self.Atc_CreateBT.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "____Skinning____", None, -1))
        self.BindSkinBT.setText(QtWidgets.QApplication.translate("MainWindow", "Bind Skin", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Proxy Mesh", None, -1))
        self.Proxy_CreateBT.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.Proxy_DeleteBT.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sub_tab), QtWidgets.QApplication.translate("MainWindow", "Sub", None, -1))