(dp1
S'info'
p2
VCreate a single arrow-shaped controller
p3
sS'name'
p4
VSingle Arrow Controller
p5
sS'tags'
p6
Vcontroller,rigging
p7
sS'syntax'
p8
S'python'
p9
sS'command'
p10
V#Import Maya modules\u000aimport maya.cmds as cmds\u000aimport maya.mel as mel\u000a\u000aselection = cmds.ls(sl=True)\u000a\u000acontrollers = []\u000a\u000aif len(selection) == 0: selection = [None]\u000a\u000afor object in selection:\u000a    controller = cmds.curve(d=1, p=[(0,0,-3),(2,0,-1),(1,0,-1),(1,0,2),(-1,0,2),(-1,0,-1),(-2,0,-1),(0,0,-3)], n=("singleArrow_CTRL"))\u000a    cmds.xform(controller,s=(0.4,0.4,0.4))\u000a    mel.eval('FreezeTransformations')\u000a    if object != None:\u000a        parentConstraint = cmds.parentConstraint(object,controller)\u000a        cmds.delete(parentConstraint)\u000a    controllers.append(controller)\u000a    \u000acmds.select(controllers)\u000a
p11
sS'id'
p12
S'3483dd51e2c020L'
p13
sS'icon'
p14
VcontrollerSingleArrow.png
p15
s.w.png
p15
s.
